#!/bin/zsh

#------------------- Default settings ----------------------------------
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	mkd="mkdir -pv" \
	bld="make && sudo make clean install" \
	ka="killall" \
	live="live-server" \
	p="sudo pacman" \

#------------------- Colorize commands ---------------------------------
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	ll="ls -a -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi"\

#------------------- Cli apps  -----------------------------------------
alias \
	f="$FILE" \
	sf="sudo $FILE" \
	v="$EDITOR" \
	sv="sudo $EDITOR" \
	z="$READER" \

#------------------- Git commands -------------------------------------
alias \
	g="git" \
	gs="git status" \
	ga="git add" \
	gc="git commit" \
	gcl="git clone" \
	gp='git push'  \
	gP='git pull'  \
	gitup="git add . && git commit && git push" \

#------------------- Tmux commands -------------------------------------
alias \
	t="tmux -u" \
	ta="tmux -u a" \
	tls="tmux ls" \
	tks="tmux kill-session -t" \
