#!/bin/zsh

#------------------- Default settings ----------------------------------
alias bld="make && sudo make clean install"
alias cl="clear"
alias cp="cp -iv"
alias diff="diff --color=auto"
alias grep="grep --color=auto"
alias ka="killall"
alias ll="ls -A"
alias ls="ls -hNv --color=auto --group-directories-first"
alias mkd="mkdir -pv"
alias mv="mv -iv"
alias p="sudo pacman"
alias rm="rm -vI"

#------------------- Cli apps  -----------------------------------------
alias r="$FILE"
alias sr="sudo $FILE"
alias v="$EDITOR"
alias sv="sudo $EDITOR"

#------------------- Git commands -------------------------------------
alias g="git"
alias ga="git add"
alias gb="git branch"
alias gc="git commit"
alias gd="git diff"
alias gcl="git clone"
alias gp='git push'
alias gP='git pull'
alias gst="git status"
alias gitup="git add . && git commit -m 'Updates.' && git push"

#------------------- Tmux commands -------------------------------------
alias t="tmux -u"
alias ta="tmux -u a"
alias tls="tmux ls"
alias tks="tmux kill-session -t"
