#!/bin/zsh

#---------------------------- Default Apps -----------------------------

export EDITOR="/usr/bin/nvim"
export TERMINAL="alacritty"
export BROWSER="brave"
export READER="zathura"
export FILE="ranger"
export GUIFILE="pcmanfm"
export MAIL="thunderbird"
