#!/bin/zsh

#---------------------------- Default Apps -----------------------------

export EDITOR="nvim"
export EDITOR="~/./nvim.appimage"
export TERMINAL="alacritty"
export BROWSER="brave"
export READER="zathura"
export FILE="ranger"
export GUIFILE="pcmanfm"
export MAIL="thunderbird"
