#!/bin/zsh

alias \
    cac="${XDG_CACHE_HOME:-$HOME/.cache}" \
    cf="${XDG_CONFIG_HOME:-$HOME/.config}" \
    D="${XDG_DOWNLOAD_DIR:-$HOME/Downloads}" \
    d="${XDG_DOCUMENTS_DIR:-$HOME/Documents}" \
    dp="${XDG_PICTURES_DIR:-$HOME/Pictures}" \
    ms="${XDG_MUSIC_DIR:-$HOME/Music}" \
    vv="${XDG_VIDEOS_DIR:-$HOME/Videos}" \
    ds="${XDG_DATA_HOME:-$HOME/.local/share}" \
    h="$HOME" \
    gd="$HOME/dotfiles" \
    sc="$HOME/.local/bin" \
    src="$HOME/.local/src" \
    mn="/mnt" \
    esc="/mnt/storage/study/escuela" \
    facu="/mnt/storage/study/facu" \
    js="/mnt/storage/code/js" \
    web="/mnt/storage/code/webmaster" \
