#!/bin/zsh

alias cfa="$EDITOR ~/.config/zsh/alias"
alias cfd="$EDITOR ~/.config/zsh/bm-dirs"
alias cfe="$EDITOR ~/.config/zsh/exports"
alias cff="$EDITOR ~/.config/zsh/bm-files"
alias cfv="$EDITOR ~/.config/nvim/init.vim"
alias cblo="cd ~/.local/src/dwmblocks && $EDITOR blocks.h"
alias cdwm="cd ~/.local/src/dwm && $EDITOR config.h"
alias cst="cd ~/.local/src/st && $EDITOR config.h"
