#!/bin/zsh

alias \
	cfa="cd ~/.config/zsh && $EDITOR aliasrc" \
	cblocks="cd ~/.local/src/dwmblocks && $EDITOR blocks.h" \
	cdwm="cd ~/.local/src/dwm && $EDITOR config.h" \
	cst="cd ~/.local/src/st && $EDITOR config.h" \
