# Colors (One Darker)
colors:
  cursor:
    text: "#191919"
    cursor: "#d8dee9"

  vi_mode_cursor:
    text: CellBackground
    cursor: CellForeground # # # Default colors

  # primary: background: "#1e2127"
  #   foreground: "#abb2bf"

  # # Normal colors
  # normal:
  #  black: "#1e2127"
  #  red: "#e06c75"
  #  green: "#98c379"
  #  yellow: "#d19a66"
  #  blue: "#61afef"
  #  magenta: "#c678dd"
  #  cyan: "#56b6c2"
  #  white: "#abb2bf"

  # # Bright colors
  # bright:
  #  black: "#5c6370"
  #  red: "#e06c75"
  #  green: "#98c379"
  #  yellow: "#d19a66"
  #  blue: "#61afef"
  #  magenta: "#c678dd"
  #  white: "#ffffff"
  #  cyan: "#56b6c2"

  #GruvBox
  primary:
    # background: "#282828" # hard contrast: #1d2021 / soft contrast: #32302f
    background: "#282828"
    foreground: "#ebdbb2"

    # Normal colors
  normal:
    black: "#282828" #"#38312b"  #"#928374"
    red: "#cc241d"
    green: "#98971a"
    yellow: "#d79921"
    blue: "#458588"
    magenta: "#b16286"
    cyan: "#689d6a"
    white: "#cecece" #"#a89984"

    # Bright colors
  bright:
    black: "#928374" #"#594f45"
    red: "#fb4934"
    green: "#b8bb26"
    yellow: "#fabd2f"
    blue: "#83a598"
    magenta: "#d3869b"
    cyan: "#8ec07c"
    white: "#eaeaeb" # "#ebdbb2"

background_opacity: 0.8

# font:
#   normal:
#     family: "Hack"
#     style: Regular
#   bold:
#     family: "Hack"
#     style: Bold
#   italic:
#     family: "Hack"
#     style: Italic
#   bold_italic:
#     family: "Hack"
#     style: Bold Italic

font:
  normal:
    family: "FiraCode"
    style: Regular
  bold:
    family: "FiraCode"
    style: Bold
  italic:
    family: "FiraCode"
    style: Italic
  bold_italic:
    family: "FiraCode"
    style: Bold Italic

  size: 14.0

  # offset is spacing between characters
  offset:
    x: 0
    y: 2

window:
  padding:
    x: 0
    y: 0

scrolling:
  # Maximum number of lines in the scrollback buffer.
  # Specifying '0' will disable scrolling.
  history: 10000

  # Number of lines the viewport will move for every line scrolled when
  # scrollback is enabled (history > 0).
  multiplier: 10

# If `true`, bold text is drawn using the bright color variants.
draw_bold_text_with_bright_colors: true

selection:
  semantic_escape_chars: ',│`|:"'' ()[]{}<>'

  # When set to `true`, selected text will be copied to both the primary and
  # the selection clipboard. Otherwise, it will only be copied to the selection
  # clipboard.
  save_to_clipboard: true

# Live config reload (changes require restart)
live_config_reload: true

key_bindings:
  # - { key: V, mods: Control|Shift, action: Paste }
  # - { key: C, mods: Control|Shift, action: Copy }
  - { key: V, mods: Alt, action: Paste }
  - { key: C, mods: Alt, action: Copy }
  - { key: Key0, mods: Control, action: ResetFontSize }
  - { key: Equals, mods: Control, action: IncreaseFontSize }
  - { key: Add, mods: Control, action: IncreaseFontSize }
  - { key: Subtract, mods: Control, action: DecreaseFontSize }
  - { key: Minus, mods: Control, action: DecreaseFontSize }
